---
name: Feature Request
about: Suggest a new feature or enhancement for the pipeline
labels: enhancement
---
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature
      description: Please provide a clear and concise description of the feature you'd like to see.
    validations:
      required: true
  - type: checkbox
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
    validations:
      required: true
    options:
      - label: Low - Nice to have
      - label: Medium - Would improve workflow
      - label: High - Critical for my use case
    default: Low
  - type: textarea
    id: problem_use_case
    attributes:
      label: Problem/Use Case
      description: Describe the problem this feature would solve or the use case it would address.
    validations:
      required: false
  - type: textarea
    id: alternatives_considered
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the feature request here.
    validations:
      required: false

