---
name: Question
about: Ask a question about the pipeline
labels: question
---
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: State your question clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: relevant_documentation
    attributes:
      label: Relevant Documentation
      description: Have you checked the documentation? If yes, what sections? This will help us to improve these sections in the future.
    validations:
      required: false
  - type: checkbox
    id: priority
    attributes:
      label: Priority
      description: How urgent is this question for you?
    validations:
      required: false
    options:
      - label: Low - I can wait. I don't need an answer urgently.
      - label: Medium - Somewhat urgent. I need an answer in the week or so.
      - label: High - Blocking urgent work from being completed. I need an answer ASAP.
    default: Low
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the question here.
    validations:
      required: false


